# Generated by Django 6.0.3 on 2026-04-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='perfil',
        ),
    ]
